//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twelve.Oclock.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosTramite
    {
        public int Id { get; set; }
        public int EstadoId { get; set; }
        public int TramiteId { get; set; }
        public string Novedad { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Tramite Tramite { get; set; }
    }
}
