//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twelve.Oclock.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traslado
    {
        public int Id { get; set; }
        public int TramiteId { get; set; }
        public int ColaboradorOrigenId { get; set; }
        public int ColaboradorDestinoId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Tramite Tramite { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
